language: rust
sudo: required
dist: trusty
addons:
    apt:
        packages:
            - libssl-dev
cache: cargo
rust:
  - nightly
matrix:
  allow_failures:
    - rust: nightly

before_cache: |
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin -f --git https://github.com/xd009642/tarpaulin --branch coveralls-test


script:
- cargo clean

after_success: |
    # Uncomment the following line for coveralls.io
    cargo tarpaulin --coveralls $TRAVIS_JOB_ID --debug --ciserver travis-ci
    echo "Printing json"
    cat coveralls.json
