name: Build
on:
  push:
    branches:
      - "*"
env:
  RUST_BACKTRACE: 1

jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - nightly
        target:
          - x86_64-unknown-linux-gnu
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.version }}
          override: true
          components: rustfmt
      - name: code-coverage
        run: |
          cargo install cargo-tarpaulin --force --git https://github.com/xd009642/tarpaulin  --branch fix/coveralls-branch
          cargo tarpaulin --coveralls ${{ secrets.COVERALLS_TOKEN }}
